apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-java-app-blue
  labels:
    app: my-java-app
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-java-app
      version: blue
  template:
    metadata:
      labels:
        app: my-java-app
        version: blue
    spec:
      containers:
      - name: my-java-app
        image: arifislam/my-java-app:base  # Blue version image
        ports:
        - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-java-app-green
  labels:
    app: my-java-app
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-java-app
      version: green
  template:
    metadata:
      labels:
        app: my-java-app
        version: green
    spec:
      containers:
      - name: my-java-app
        image: arifislam/my-java-app:base  # Green version image
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-java-app-service
spec:
  selector:
    app: my-java-app
    version: blue  # Initially routing traffic to the Blue version
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
